[package]
authors = ["Greg Green <ggreen@bit-builder.com>"]
name = "atmo-monitor-stm32"
edition = "2024"
version = "0.2.0"

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = { version = "1.0.1", optional = true }
defmt-rtt = { version = "1.1.0", optional = true }
panic-probe = { version = "1.0.0", features = ["print-defmt"], optional = true }
panic-halt = "1"
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-futures = "0.1.2"
embassy-sync = "0.7.2"
embassy-time = { version = "0.5.0", features = ["tick-hz-32_768"] }
embassy-stm32 = { version = "0.4.0", features = ["stm32f103cb", "unstable-pac", "memory-x", "time-driver-any"]  }
embassy-usb = "0.5.1"
il0373 = { version = "0.2.0", features = ["sram"] }
embedded-graphics = "0.8"
profont = "0.7"
heapless = "0.8"
bme680 = "0.6.0"
pms-7003 = { git = "https://github.com/gpgreen/pms-7003", branch = "master", features = ["async"] }
static_cell = "1.1"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
micromath = "2.1.0"
log = "0.4.28"

[dev-dependencies]
defmt-test = "0.3"

# cargo build/run
[profile.dev]
debug = true
lto = true
incremental = true
opt-level = 's'

# cargo build/run --release
[profile.release]
debug = 2
incremental = false
lto = true
opt-level = "s"

[features]
defmt = ["dep:defmt"]
defmt-rtt = ["dep:defmt-rtt"]
panic-probe = ["dep:panic-probe"]
default = ["debug"]
debug = [
      "defmt",
      "defmt-rtt",
      "panic-probe",
      "embassy-executor/defmt",
      "embassy-sync/defmt",
      "embassy-futures/defmt",
      "embassy-time/defmt",
      "embassy-time/defmt-timestamp-uptime",
      "embassy-stm32/defmt",
      "embassy-usb/defmt",
      "pms-7003/defmt",
]
